# Loads default set of integrations. Do not remove.
default_config:


homeassistant:
  allowlist_external_dirs:
  - "/config"
#
# uncomment here to activate new stuff
#
  #
  # WORKAROUND: put all custom automations here !!
  #
  packages: !include_dir_named packages/


# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes


# Text to speech
# tts:
#  - platform: pc

influxdb:
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_measurement: units
  precision: s
  # Glob-Regeln greifen erst, wenn die Domains NICHT mehr im exclude stehen
  component_config_glob:
    "binary_sensor.*":
      override_measurement: binary_sensors
    "automation.*":
      override_measurement: automations
  exclude:
    domains:
      - persistent_notification
      - person
      - input_number
      - script
      - automation    # Blockiert neue Daten
      - binary_sensor # Blockiert neue Daten
      - sun
    entity_globs:
      - sensor.*_battery_state
      - sensor.*_charger_type
      - sensor.tasmota_ssid*
      - sensor.*_uptime*
    entities:
      - zone.home
      - weather.home
  include:
    domains:
      - sensor

#
#recorder:
#  purge_keep_days: 60
#
recorder:
  auto_purge: true
  purge_keep_days: 58
  auto_repack: true
  exclude:
    domains:
      - automation
      - switch
      - light
      - update
      - person
      - zone
      - weather
      - schedule
      - device_tracker
      - media_player
      - sun
      - remote
      - select
      - number
      - input_number
      - script
    entities:
      - sensor.tasmota_energy_supply


# automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


#lovelace:
#  mode: yaml
