sensor:
# - platform: openhardwaremonitor
# # host: icarus
#   host: 172.16.1.3
#   port: 8085
#
# - platform: openhardwaremonitor
# # host: daedalus
#   host: 172.16.1.2
#   port: 8085

  - name: "homeassistant.db.sqlite.size"
    unique_id: "homeassistant_db_sqlite_size"
    platform: filesize
    file_paths:
    - /config/home-assistant_v2.db
    scan_interval: 3600

automation: !include ../automations.yaml
