###############################################################################
#  PACKAGE: Strompreis pro kWh (automatische historische Preiswechsel)
#  Version: 2025-11
###############################################################################
#  Beschreibung:
#   - Input Number dient als zentrale Quelle für alle Berechnungen
#   - Template-Sensor leitet sich von der Input Number ab (für Influx/Grafana)
#   - Automatische Preiswechsel nach Datum (Yellow → E.ON → Naturwerke)
###############################################################################

###############################################################################
#  INPUT NUMBER (Master für Berechnungen)
###############################################################################
input_number:
  strom_preis_pro_kwh:
    name: "Strompreis pro kWh"
    icon: mdi:currency-eur
    min: 0
    max: 10
    step: 0.0001
    unit_of_measurement: "€"
    mode: box
    initial: 0.3209  # aktueller Tarif (Naturwerke)

###############################################################################
#  TEMPLATE-SENSOR (für Dashboards / Influx / Grafana)
###############################################################################
template:
  - sensor:
      - name: "Strom_Preis_pro_kWh"
        unique_id: sensor_strom_preis_pro_kwh
        unit_of_measurement: "€"
        icon: mdi:currency-eur
        state_class: measurement
        state: >
          {# Leitet sich direkt von der Input Number ab (immer synchron) #}
          {{ states('input_number.strom_preis_pro_kwh') | float(0) }}

###############################################################################
#  AUTOMATIONEN (Historische Preisänderungen)
###############################################################################
automation:

  # 1️⃣ Alter Yellow-Tarif bis 31.03.2024
  - alias: "Strompreis setzen - Yellow alt (bis 2024-03-31)"
    trigger:
      - platform: time
        at: "00:00:00"
    condition:
      - condition: template
        value_template: "{{ now().date() < strptime('2024-04-01', '%Y-%m-%d').date() }}"
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.strom_preis_pro_kwh
        data:
          value: 0.3351

  # 2️⃣ Neuer Yellow-Tarif ab 01.04.2024 bis 09.04.2024
  - alias: "Strompreis setzen - Yellow neu (01.04–09.04.2024)"
    trigger:
      - platform: time
        at: "00:00:00"
    condition:
      - condition: template
        value_template: >
          {{ now().date() >= strptime('2024-04-01', '%Y-%m-%d').date() and
             now().date() < strptime('2024-04-10', '%Y-%m-%d').date() }}
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.strom_preis_pro_kwh
        data:
          value: 0.400

  # 3️⃣ E.ON Übergangstarif ab 10.04.2024 bis 24.04.2024
  - alias: "Strompreis setzen - E.ON (10.04–24.04.2024)"
    trigger:
      - platform: time
        at: "00:00:00"
    condition:
      - condition: template
        value_template: >
          {{ now().date() >= strptime('2024-04-10', '%Y-%m-%d').date() and
             now().date() < strptime('2024-04-25', '%Y-%m-%d').date() }}
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.strom_preis_pro_kwh
        data:
          value: 0.4265

  # 4️⃣ Naturwerke ab 25.04.2024
  - alias: "Strompreis setzen - Naturwerke (ab 25.04.2024)"
    trigger:
      - platform: time
        at: "00:00:00"
    condition:
      - condition: template
        value_template: "{{ now().date() >= strptime('2024-04-25', '%Y-%m-%d').date() }}"
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.strom_preis_pro_kwh
        data:
          value: 0.3209
