###############################################################################
#  PACKAGE: Maxxicharge – Premium B1 with separate timestamps (final)
###############################################################################
# Features:
# - Central script for integration (30s clamp, 600s restart protection)
# - Separate timestamps for battery and PV to avoid race conditions
# - Updates original last_bkw_update for compatibility
# - Debug logging via input_boolean.solar_savings_debug
# - Preserves all original input_number and sensor entity names (no renames)
###############################################################################

###############################################################################
#  INPUT NUMBERS (persistent sums) — original names preserved
###############################################################################
input_number:
  saving_pv_total:
    name: "Gesamt-Ersparnis PV"
    icon: mdi:currency-eur
    min: 0
    max: 1000000
    step: 0.000001
    unit_of_measurement: "€"
    mode: box

  saving_battery:
    name: "Ersparnis Batterie"
    icon: mdi:battery
    min: 0
    max: 1000000
    step: 0.000001
    unit_of_measurement: "€"
    mode: box

  saving_pv_passthrough:
    name: "Ersparnis PV-Direktnutzung"
    icon: mdi:solar-power
    min: 0
    max: 1000000
    step: 0.000001
    unit_of_measurement: "€"
    mode: box


###############################################################################
#  DEBUG SWITCH (keeps original name)
###############################################################################
input_boolean:
  solar_savings_debug:
    name: "Solar Savings Debug Logging"
    icon: mdi:bug


###############################################################################
#  TIMESTAMPS
###############################################################################
input_datetime:
  last_bkw_update:
    name: "Letztes BKW-Update"
    has_date: true
    has_time: true

  last_bkw_update_battery:
    name: "Letztes BKW-Update Batterie"
    has_date: true
    has_time: true

  last_bkw_update_pv:
    name: "Letztes BKW-Update PV"
    has_date: true
    has_time: true


###############################################################################
#  TEMPLATE SENSORS (display-only) — keep unique_ids as before
###############################################################################
template:
  - sensor:
      - name: "saving.pv_total"
        unique_id: "saving_pv_total_template"
        unit_of_measurement: "€"
        icon: mdi:currency-eur
        state: "{{ states('input_number.saving_pv_total') | float(0) | round(2) }}"

      - name: "saving.battery"
        unique_id: "saving_battery_template"
        unit_of_measurement: "€"
        icon: mdi:battery
        state: "{{ states('input_number.saving_battery') | float(0) | round(2) }}"

      - name: "saving.pv_passthrough"
        unique_id: "saving_pv_passthrough_template"
        unit_of_measurement: "€"
        icon: mdi:solar-power
        state: "{{ states('input_number.saving_pv_passthrough') | float(0) | round(2) }}"


###############################################################################
#  INITIALIZATION AT STARTUP (preserve original behaviour)
###############################################################################
automation:
  - alias: "Ersparnis-Zähler initialisieren"
    id: init_solar_savings
    trigger:
      - platform: homeassistant
        event: start
    condition:
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ states('input_number.saving_pv_total') in ['unknown', 'unavailable', 'none'] }}"
          - condition: template
            value_template: "{{ states('input_number.saving_battery') in ['unknown', 'unavailable', 'none'] }}"
          - condition: template
            value_template: "{{ states('input_number.saving_pv_passthrough') in ['unknown', 'unavailable', 'none'] }}"
    action:
      - service: input_number.set_value
        target:
          entity_id:
            - input_number.saving_pv_total
            - input_number.saving_battery
            - input_number.saving_pv_passthrough
        data:
          value: 0
      - service: logbook.log
        data:
          name: "Solar Savings Init"
          message: "Initialisiert alle Ersparnis-Zähler auf 0 (erstmaliger Start)"


###############################################################################
#  CENTRAL SCRIPT: integrate_solar_savings_core
#  - takes trigger timestamp (seconds), source power (W), price sensor, and target eur input_number
#  - applies 30s clamp and 600s restart-safety (soft)
###############################################################################
script:
  integrate_solar_savings_core:
    alias: "Integrate Solar Savings (core)"
    description: "Central integration logic with clamp+restart protection. Called by automations."
    fields:
      source_power:
        description: "Watt value (number) or entity string (not used here)"
      trigger_ts:
        description: "Trigger timestamp in seconds (as number)"
      price_sensor:
        description: "Price per kWh sensor entity_id"
      eur_input:
        description: "input_number entity_id to increment in €"
      update_ts_name:
        description: "input_datetime entity_id to update for this source"
    sequence:
      - variables:
          now_ts: "{{ as_timestamp(now()) }}"
          trig_ts: "{{ trigger_ts | float(0) }}"
          raw_dt_s: "{{ (now_ts - trig_ts) | float(0) }}"

          # Restart protection: treat very large gaps as zero (soft)
          clamped_dt_s: >-
            {% set r = raw_dt_s | float(0) %}
            {% if r > 600 %}
              0
            {% else %}
              {{ [r, 30] | min }}
            {% endif %}

          dt_h: "{{ clamped_dt_s / 3600 }}"

          power: "{{ source_power | float(0) }}"
          energy_kwh: "{{ (power * dt_h) / 1000 }}"
          price_per_kwh: "{{ states(price_sensor) | float(0) }}"
          delta_eur: "{{ (energy_kwh * price_per_kwh) | float(0) }}"

      - choose:
          - conditions: "{{ is_state('input_boolean.solar_savings_debug','on') }}"
            sequence:
              - service: logbook.log
                data:
                  name: "Solar Savings (core)"
                  message: >
                    source={{ update_ts_name }}, power={{ power }} W, dt={{ dt_h | round(6) }} h,
                    energy_kWh={{ energy_kwh | round(6) }}, delta_EUR={{ delta_eur | round(6) }}, price={{ price_per_kwh }}

      - if:
          - condition: template
            value_template: "{{ delta_eur | float(0) > 0 }}"
        then:
          - service: input_number.set_value
            target:
              entity_id: "{{ eur_input }}"
            data:
              value: >
                {{ (states(eur_input) | float(0) + delta_eur) | round(6) }}

          - service: input_number.set_value
            target:
              entity_id: input_number.saving_pv_total
            data:
              value: >
                {{ (states('input_number.saving_pv_total') | float(0) + delta_eur) | round(6) }}

      - service: input_datetime.set_datetime
        target:
          entity_id: "{{ update_ts_name }}"
        data:
          timestamp: "{{ now_ts }}"

      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.last_bkw_update
        data:
          timestamp: "{{ now_ts }}"


###############################################################################
#  AUTOMATION: Battery savings (calls core script)
###############################################################################
  - alias: "Einsparung Batterie sofort aufsummieren"
    id: solar_savings_increment_battery
    mode: queued
    trigger:
      - platform: state
        entity_id: sensor.power_self_used_from_ccu_bat_discharge
    action:
      - service: script.integrate_solar_savings_core
        data:
          source_power: "{{ states('sensor.power_self_used_from_ccu_bat_discharge') }}"
          trigger_ts: "{{ as_timestamp(trigger.to_state.last_changed) }}"
          price_sensor: "sensor.strom_preis_pro_kwh"
          eur_input: "input_number.saving_battery"
          update_ts_name: "input_datetime.last_bkw_update_battery"


###############################################################################
#  AUTOMATION: PV passthrough savings (calls core script)
###############################################################################
  - alias: "Einsparung PV Passthrough sofort aufsummieren"
    id: solar_savings_increment_pv_passthrough
    mode: queued
    trigger:
      - platform: state
        entity_id: sensor.power_self_used_from_ccu_passthrough
    action:
      - service: script.integrate_solar_savings_core
        data:
          source_power: "{{ states('sensor.power_self_used_from_ccu_passthrough') }}"
          trigger_ts: "{{ as_timestamp(trigger.to_state.last_changed) }}"
          price_sensor: "sensor.strom_preis_pro_kwh"
          eur_input: "input_number.saving_pv_passthrough"
          update_ts_name: "input_datetime.last_bkw_update_pv"
