###############################################################################
#  PACKAGE: Solar Savings ‚Äì 2025 (Variante mit ausgelagerter Logik)
###############################################################################
#  √Ñnderungen:
#   - Beide Aufsummier-Automationen verwenden jetzt EIN gemeinsames Script
#   - Debug-Logging bleibt vollst√§ndig erhalten
#   - Schutz vor gro√üen Zeitdeltas bleibt erhalten (clamped to 30s)
#   - Gesamte Datei neu generiert
###############################################################################


###############################################################################
#  INPUT NUMBERS (persistente Summen)
###############################################################################
input_number:
  saving_pv_total:
    name: "Gesamt-Ersparnis PV"
    icon: mdi:currency-eur
    min: 0
    max: 1000000
    step: 0.000001
    unit_of_measurement: "‚Ç¨"
    mode: box

  saving_battery:
    name: "Ersparnis Batterie"
    icon: mdi:battery
    min: 0
    max: 1000000
    step: 0.000001
    unit_of_measurement: "‚Ç¨"
    mode: box

  saving_pv_passthrough:
    name: "Ersparnis PV-Direktnutzung"
    icon: mdi:solar-power
    min: 0
    max: 1000000
    step: 0.000001
    unit_of_measurement: "‚Ç¨"
    mode: box


###############################################################################
#  DEBUG-SCHALTER
###############################################################################
input_boolean:
  solar_savings_debug:
    name: "Solar Savings Debug Logging"
    icon: mdi:bug


###############################################################################
#  HILFSSENSOREN
###############################################################################
input_datetime:
  last_bkw_update:
    name: "Letztes BKW-Update"
    has_date: true
    has_time: true


###############################################################################
#  TEMPLATE-SENSOREN
###############################################################################
template:
  - sensor:
      - name: "saving.pv_total"
        unique_id: "saving_pv_total_template"
        unit_of_measurement: "‚Ç¨"
        icon: mdi:currency-eur
        state: "{{ states('input_number.saving_pv_total') | float(0) | round(2) }}"

      - name: "saving.battery"
        unique_id: "saving_battery_template"
        unit_of_measurement: "‚Ç¨"
        icon: mdi:battery
        state: "{{ states('input_number.saving_battery') | float(0) | round(2) }}"

      - name: "saving.pv_passthrough"
        unique_id: "saving_pv_passthrough_template"
        unit_of_measurement: "‚Ç¨"
        icon: mdi:solar-power
        state: "{{ states('input_number.saving_pv_passthrough') | float(0) | round(2) }}"


###############################################################################
#  SCRIPT: Gemeinsame Berechnungslogik PV + Batterie
###############################################################################
script:
  solar_savings_update:
    alias: "Solar Savings ‚Äì Gemeinsame Logik"
    description: "Berechnet die Einsparungen anhand Leistung, Zeitdelta und Preis"
    fields:
      power_entity:
        description: "Sensor-Entity, die die aktuelle Leistung liefert"
      target_input:
        description: "input_number, das erh√∂ht werden soll"
      debug_label:
        description: "Text/Emoji f√ºr Debug-Log"
    sequence:
      - variables:
          now_ts: "{{ as_timestamp(now()) }}"
          last_ts: >-
            {% set t = states('input_datetime.last_bkw_update') %}
            {{ as_timestamp(t) if t not in ['unknown','unavailable','none',''] else as_timestamp(now()) }}
          dt_sec: "{{ now_ts - last_ts }}"
          dt_sec_clamped: "{{ min(dt_sec, 30) }}"
          dt_h: "{{ dt_sec_clamped / 3600 }}"

          power: "{{ states(power_entity) | float(0) }}"
          energy: "{{ (power * dt_h) / 1000 }}"
          price: "{{ states('sensor.strom_preis_pro_kwh') | float(0) }}"

          delta_eur: "{{ energy * price }}"

      - choose:
          - conditions: "{{ is_state('input_boolean.solar_savings_debug','on') }}"
            sequence:
              - service: logbook.log
                data:
                  name: "Solar Savings"
                  message: >
                    {{ debug_label }}:
                    power={{ power }} W,
                    dt={{ dt_h | round(6) }} h,
                    Œî={{ delta_eur | round(6) }} ‚Ç¨,
                    price={{ price }} ‚Ç¨/kWh

      - if:
          - condition: template
            value_template: "{{ delta_eur > 0 }}"
        then:
          # Spezifischer Sparz√§hler
          - service: input_number.set_value
            target:
              entity_id: "{{ target_input }}"
            data:
              value: >
                {{ (states(target_input) | float(0) + delta_eur) | round(6) }}

          # Gesamtsumme PV
          - service: input_number.set_value
            target:
              entity_id: input_number.saving_pv_total
            data:
              value: >
                {{ (states('input_number.saving_pv_total') | float(0) + delta_eur) | round(6) }}

      # Update Timestamp
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.last_bkw_update
        data:
          timestamp: "{{ now_ts }}"


###############################################################################
#  AUTOMATIONEN
###############################################################################
automation:

  ###########################################################################
  # üü¢ 0Ô∏è‚É£ Initialisierung bei Systemstart
  ###########################################################################
  - alias: "Ersparnis-Z√§hler initialisieren"
    id: init_solar_savings
    trigger:
      - platform: homeassistant
        event: start
    condition:
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ states('input_number.saving_pv_total') in ['unknown', 'unavailable', 'none'] }}"
          - condition: template
            value_template: "{{ states('input_number.saving_battery') in ['unknown', 'unavailable', 'none'] }}"
          - condition: template
            value_template: "{{ states('input_number.saving_pv_passthrough') in ['unknown', 'unavailable', 'none'] }}"
    action:
      - service: input_number.set_value
        target:
          entity_id:
            - input_number.saving_pv_total
            - input_number.saving_battery
            - input_number.saving_pv_passthrough
        data:
          value: 0
      - service: logbook.log
        data:
          name: "Solar Savings Init"
          message: "Initialisiert alle Ersparnis-Z√§hler auf 0 (erstmaliger Start)"


  ###########################################################################
  # 1Ô∏è‚É£ Einsparung Batterie ‚Äì nutzt gemeinsame Logik
  ###########################################################################
  - alias: "Einsparung Batterie sofort aufsummieren"
    id: solar_savings_increment_battery
    mode: queued
    trigger:
      - platform: state
        entity_id: sensor.power_self_used_from_ccu_bat_discharge
    action:
      - service: script.solar_savings_update
        data:
          power_entity: sensor.power_self_used_from_ccu_bat_discharge
          target_input: input_number.saving_battery
          debug_label: "üîã Batterie"


  ###########################################################################
  # 2Ô∏è‚É£ Einsparung PV-Direktnutzung ‚Äì nutzt gemeinsame Logik
  ###########################################################################
  - alias: "Einsparung PV Passthrough sofort aufsummieren"
    id: solar_savings_increment_pv_passthrough
    mode: queued
    trigger:
      - platform: state
        entity_id: sensor.power_self_used_from_ccu_passthrough
    action:
      - service: script.solar_savings_update
        data:
          power_entity: sensor.power_self_used_from_ccu_passthrough
          target_input: input_number.saving_pv_passthrough
          debug_label: "‚òÄÔ∏è PV Passthrough"
