###############################################################################
#  PACKAGE: MaxxiCharge ‚Äì Premium Savings System (B1+)
###############################################################################
#  Features:
#   - Ein einziges Script, das ALLE Berechnungen √ºbernimmt
#   - Batterienutzung & PV-Passthrough nutzen identische Code-Logik
#   - 30-Sekunden-Zeit-Clamping
#   - Startup-sicher (unknown‚Üíjetzt)
#   - Debug-Logging √ºber input_boolean
#   - Persistente input_number-Summen
###############################################################################

###############################################################################
#  INPUT NUMBERS
###############################################################################
input_number:
  maxxicharge_savings_total:
    name: "Maxxicharge Gesamtersparnis"
    icon: mdi:currency-eur
    min: 0
    max: 1000000
    step: 0.000001
    unit_of_measurement: "‚Ç¨"

  maxxicharge_savings_battery:
    name: "Ersparnis Batterie"
    icon: mdi:battery
    min: 0
    max: 1000000
    step: 0.000001
    unit_of_measurement: "‚Ç¨"

  maxxicharge_savings_pv:
    name: "Ersparnis PV-Direkt"
    icon: mdi:solar-power
    min: 0
    max: 1000000
    step: 0.000001
    unit_of_measurement: "‚Ç¨"

###############################################################################
#  DEBUG
###############################################################################
input_boolean:
  maxxicharge_savings_debug:
    name: "Maxxicharge Debug"
    icon: mdi:bug

###############################################################################
#  TIMESTAMPS
###############################################################################
input_datetime:
  last_update_battery:
    name: "Letztes Batterie-Update"
    has_date: true
    has_time: true

  last_update_pv:
    name: "Letztes PV-Update"
    has_date: true
    has_time: true

###############################################################################
#  TEMPLATE-SENSOREN (zur Anzeige)
###############################################################################
template:
  - sensor:
      - name: "maxxicharge.savings_total"
        unique_id: "maxxicharge_savings_total_template"
        unit_of_measurement: "‚Ç¨"
        state: "{{ states('input_number.maxxicharge_savings_total') | float(0) | round(2) }}"

      - name: "maxxicharge.savings_battery"
        unique_id: "maxxicharge_savings_battery_template"
        unit_of_measurement: "‚Ç¨"
        state: "{{ states('input_number.maxxicharge_savings_battery') | float(0) | round(2) }}"

      - name: "maxxicharge.savings_pv"
        unique_id: "maxxicharge_savings_pv_template"
        unit_of_measurement: "‚Ç¨"
        state: "{{ states('input_number.maxxicharge_savings_pv') | float(0) | round(2) }}"

###############################################################################
#  MASTER-SKRIPT (Zentrale Logik)
###############################################################################
script:
  maxxicharge_savings_core:
    alias: "Maxxicharge Savings Core Logic"
    mode: queued
    fields:
      source_power:
        description: "Leistungswert in Watt"
      last_update:
        description: "Name des input_datetime der Quelle"
      price_sensor:
        description: "Preis pro kWh"
      target_entity:
        description: "input_number zum Aufsummieren"
    sequence:
      - variables:
          now_ts: "{{ as_timestamp(now()) }}"
          last_ts: >-
            {% set t = states(last_update) %}
            {{ as_timestamp(t) if t not in ['unknown','unavailable','none',''] else as_timestamp(now()) }}

          raw_dt_s: "{{ now_ts - last_ts }}"
          clamped_dt_s: "{{ [raw_dt_s, 30] | min }}"
          dt_h: "{{ clamped_dt_s / 3600 }}"

          power: "{{ source_power | float(0) }}"
          energy_kwh: "{{ (power * dt_h) / 1000 }}"
          price: "{{ states(price_sensor) | float(0) }}"
          delta_eur: "{{ energy_kwh * price }}"

      - choose:
          - conditions: "{{ is_state('input_boolean.maxxicharge_savings_debug','on') }}"
            sequence:
              - service: logbook.log
                data:
                  name: "Maxxicharge Savings"
                  message: >
                    üîß Quelle={{ target_entity }},
                    Power={{ power }} W,
                    dt={{ dt_h | round(6) }} h,
                    ŒîE={{ energy_kwh | round(6) }} kWh,
                    Œî‚Ç¨={{ delta_eur | round(6) }},
                    Preis={{ price }}

      - if:
          - condition: template
            value_template: "{{ delta_eur > 0 }}"
        then:
          - service: input_number.set_value
            target:
              entity_id: "{{ target_entity }}"
            data:
              value: >
                {{ (states(target_entity)|float + delta_eur) | round(6) }}

          - service: input_number.set_value
            target:
              entity_id: input_number.maxxicharge_savings_total
            data:
              value: >
                {{ (states('input_number.maxxicharge_savings_total')|float + delta_eur) | round(6) }}

      - service: input_datetime.set_datetime
        target:
          entity_id: "{{ last_update }}"
        data:
          timestamp: "{{ now_ts }}"

###############################################################################
#  AUTOMATIONEN
###############################################################################

# üü¢ Batterie
- alias: "Maxxicharge Savings ‚Äì Batterie"
  id: maxxicharge_savings_battery
  trigger:
    - platform: state
      entity_id: sensor.power_self_used_from_ccu_bat_discharge
  action:
    - service: script.maxxicharge_savings_core
      data:
        source_power: "{{ states('sensor.power_self_used_from_ccu_bat_discharge') }}"
        last_update: "input_datetime.last_update_battery"
        price_sensor: "sensor.strom_preis_pro_kwh"
        target_entity: "input_number.maxxicharge_savings_battery"

# ‚òÄÔ∏è PV
- alias: "Maxxicharge Savings ‚Äì PV"
  id: maxxicharge_savings_pv
  trigger:
    - platform: state
      entity_id: sensor.power_self_used_from_ccu_passthrough
  action:
    - service: script.maxxicharge_savings_core
      data:
        source_power: "{{ states('sensor.power_self_used_from_ccu_passthrough') }}"
        last_update: "input_datetime.last_update_pv"
        price_sensor: "sensor.strom_preis_pro_kwh"
        target_entity: "input_number.maxxicharge_savings_pv"
