###############################################################################
#  PACKAGE: Solar Savings – Premium Version (2025, Variante B1)
###############################################################################
#  Features:
#   - 30s Clamping für beide Leistungen
#   - Persistente Summen ohne Reset
#   - Startup-Schutz, setzt nur zurück wenn unknown
#   - Zentrale Berechnungslogik ausgelagert in script.solar_savings_add
#   - Keine Namensänderungen
#   - Debug-Schalter
###############################################################################


###############################################################################
#  INPUT NUMBERS (persistente Summen)
###############################################################################
input_number:
  saving_pv_total:
    name: "Gesamt-Ersparnis PV"
    icon: mdi:currency-eur
    min: 0
    max: 1000000
    step: 0.000001
    unit_of_measurement: "€"
    mode: box

  saving_battery:
    name: "Ersparnis Batterie"
    icon: mdi:battery
    min: 0
    max: 1000000
    step: 0.000001
    unit_of_measurement: "€"
    mode: box

  saving_pv_passthrough:
    name: "Ersparnis PV-Direktnutzung"
    icon: mdi:solar-power
    min: 0
    max: 1000000
    step: 0.000001
    unit_of_measurement: "€"
    mode: box


###############################################################################
#  DEBUG-SCHALTER
###############################################################################
input_boolean:
  solar_savings_debug:
    name: "Solar Savings Debug Logging"
    icon: mdi:bug


###############################################################################
#  TIMESTAMP FÜR CLAMPING
###############################################################################
input_datetime:
  last_bkw_update:
    name: "Letztes BKW-Update"
    has_date: true
    has_time: true


###############################################################################
#  TEMPLATE-SENSOREN
###############################################################################
template:
  - sensor:
      - name: "saving.pv_total"
        unique_id: "saving_pv_total_template"
        unit_of_measurement: "€"
        icon: mdi:currency-eur
        state: "{{ states('input_number.saving_pv_total') | float(0) | round(2) }}"

      - name: "saving.battery"
        unique_id: "saving_battery_template"
        unit_of_measurement: "€"
        icon: mdi:battery
        state: "{{ states('input_number.saving_battery') | float(0) | round(2) }}"

      - name: "saving.pv_passthrough"
        unique_id: "saving_pv_passthrough_template"
        unit_of_measurement: "€"
        icon: mdi:solar-power
        state: "{{ states('input_number.saving_pv_passthrough') | float(0) | round(2) }}"


###############################################################################
#  SCRIPT – Zentrale Berechnungslogik
###############################################################################
script:
  solar_savings_add:
    alias: "Solar Savings – Add Amount"
    mode: parallel
    fields:
      target_input:
        description: "Ziel-Input-Number"
      amount:
        description: "Euro-Wert"
    sequence:
      - if:
          - condition: template
            value_template: "{{ amount | float(0) > 0 }}"
        then:
          - service: input_number.set_value
            target:
              entity_id: "{{ target_input }}"
            data:
              value: >
                {{ (states(target_input) | float(0) + amount | float(0)) | round(6) }}

          - service: input_number.set_value
            target:
              entity_id: input_number.saving_pv_total
            data:
              value: >
                {{ (states('input_number.saving_pv_total') | float(0) + amount | float(0)) | round(6) }}

      - choose:
          - conditions: "{{ is_state('input_boolean.solar_savings_debug','on') }}"
            sequence:
              - service: logbook.log
                data:
                  name: "Solar Savings"
                  message: >
                    ➕ Add: {{ amount | float(0) }} € → {{ target_input }}

      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.last_bkw_update
        data:
          timestamp: "{{ as_timestamp(now()) }}"


###############################################################################
#  AUTOMATIONEN
###############################################################################
automation:

  ###########################################################################
  # 0️⃣ Initialisierung bei Systemstart (nur wenn unknown)
  ###########################################################################
  - alias: "Ersparnis-Zähler initialisieren"
    id: init_solar_savings
    trigger:
      - platform: homeassistant
        event: start
    condition:
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ states('input_number.saving_pv_total') in ['unknown','unavailable','none'] }}"
          - condition: template
            value_template: "{{ states('input_number.saving_battery') in ['unknown','unavailable','none'] }}"
          - condition: template
            value_template: "{{ states('input_number.saving_pv_passthrough') in ['unknown','unavailable','none'] }}"
    action:
      - service: input_number.set_value
        target:
          entity_id:
            - input_number.saving_pv_total
            - input_number.saving_battery
            - input_number.saving_pv_passthrough
        data:
          value: 0
      - service: logbook.log
        data:
          name: "Solar Savings Init"
          message: "Initialisierung erfolgte (unknown → 0)"


  ###########################################################################
  # 1️⃣ Einsparung BATTERIE
  ###########################################################################
  - alias: "Einsparung Batterie sofort aufsummieren"
    id: solar_savings_increment_battery
    mode: queued
    trigger:
      - platform: state
        entity_id: sensor.power_self_used_from_ccu_bat_discharge
    action:
      - variables:
          now_ts: "{{ as_timestamp(now()) }}"
          lt: "{{ states('input_datetime.last_bkw_update') }}"
          last_ts: "{{ as_timestamp(lt) if lt not in ['unknown','unavailable','none',''] else now_ts }}"
          dt_raw_s: "{{ now_ts - last_ts }}"
          dt_clamped_s: "{{ [dt_raw_s, 30] | min }}"
          dt_h: "{{ dt_clamped_s / 3600 }}"
          power: "{{ states('sensor.power_self_used_from_ccu_bat_discharge') | float(0) }}"
          energy_kwh: "{{ (power * dt_h) / 1000 }}"
          price: "{{ states('sensor.strom_preis_pro_kwh') | float(0) }}"
          delta_eur: "{{ energy_kwh * price }}"
      - service: script.solar_savings_add
        data:
          target_input: input_number.saving_battery
          amount: "{{ delta_eur }}"


  ###########################################################################
  # 2️⃣ Einsparung PV-DIREKTNUTZUNG
  ###########################################################################
  - alias: "Einsparung PV Passthrough sofort aufsummieren"
    id: solar_savings_increment_pv_passthrough
    mode: queued
    trigger:
      - platform: state
        entity_id: sensor.power_self_used_from_ccu_passthrough
    action:
      - variables:
          now_ts: "{{ as_timestamp(now()) }}"
          lt: "{{ states('input_datetime.last_bkw_update') }}"
          last_ts: "{{ as_timestamp(lt) if lt not in ['unknown','unavailable','none',''] else now_ts }}"
          dt_raw_s: "{{ now_ts - last_ts }}"
          dt_clamped_s: "{{ [dt_raw_s, 30] | min }}"
          dt_h: "{{ dt_clamped_s / 3600 }}"
          power: "{{ states('sensor.power_self_used_from_ccu_passthrough') | float(0) }}"
          energy_kwh: "{{ (power * dt_h) / 1000 }}"
          price: "{{ states('sensor.strom_preis_pro_kwh') | float(0) }}"
          delta_eur: "{{ energy_kwh * price }}"
      - service: script.solar_savings_add
        data:
          target_input: input_number.saving_pv_passthrough
          amount: "{{ delta_eur }}"
