###############################################################################
#  PACKAGE: Solar Feed-in Loss – Version 7 (angepasst an PV-Idealcode)
###############################################################################

###############################################################################
#  INPUT NUMBERS (persistente Summen)
###############################################################################
input_number:
  saving_feedin_loss:
    name: "Verlust durch Einspeisung"
    icon: mdi:transmission-tower-export
    min: -1000000
    max: 0
    step: 0.000001
    unit_of_measurement: "€"
    mode: box

###############################################################################
#  DEBUG-SCHALTER
###############################################################################
input_boolean:
  solar_feedin_debug:
    name: "Solar Feed-in Debug Logging"
    icon: mdi:bug

###############################################################################
#  TEMPLATE-SENSOREN
###############################################################################
template:
  - sensor:
      - name: "saving.feedin_loss"
        unique_id: "saving_feedin_loss_template"
        unit_of_measurement: "€"
        icon: mdi:transmission-tower-export
        state: "{{ states('input_number.saving_feedin_loss') | float(-9999) | round(2) }}"

###############################################################################
#  AUTOMATIONEN
###############################################################################
automation:

  ###########################################################################
  # 0️⃣ Initialisierung beim Systemstart (Stil wie Ideal-Code)
  ###########################################################################
  - alias: "Feed-in Loss initialisieren"
    id: init_feedin_loss
    trigger:
      - platform: homeassistant
        event: start
    condition:
      - condition: or
        conditions:
          - "{{ states('input_number.saving_feedin_loss') in ['unknown','unavailable','none'] }}"
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.saving_feedin_loss
        data:
          value: 0
      - service: logbook.log
        data:
          name: "Solar Feed-in Init"
          message: "Initialisiert Einspeiseverlust-Zähler auf 0."

  ###########################################################################
  # 1️⃣ Einspeiseverluste basierend auf Zählerdifferenz (negativ wachsend)
  ###########################################################################
  - alias: "Einspeiseverluste berechnen (Feed-in Loss)"
    id: solar_savings_increment_feedin_loss_v7
    mode: queued
    trigger:
      - platform: state
        entity_id: sensor.tasmota_energy_supply_kwh

    action:
      - variables:
          prev: "{{ trigger.from_state.state | float(-9999) }}"
          curr: "{{ trigger.to_state.state | float(-9999) }}"
          delta_kwh: >-
            {% if prev | float(0) > -1 and curr | float(0) > -1 %}
              {{ curr - prev }}
            {% else %}
              -9999
            {% endif %}

          price: "{{ states('input_number.strom_preis_pro_kwh') | float(-9999) }}"
          delta_loss_eur: >-
            {% if delta_kwh | float(0) > 0 and price | float(0) > 0 %}
              {{ -1 * delta_kwh | float(0) * price | float(0) }}
            {% else %}
              0
            {% endif %}

          debug_v1: >
            [DEBUG FEEDIN V1]
            prev={{ prev }}
            curr={{ curr }}
            delta_kwh={{ delta_kwh }}
            price={{ price }}
            delta_loss_eur={{ delta_loss_eur }}

      # Debug-Log (Systemlog)
      - choose:
          - conditions: "{{ is_state('input_boolean.solar_feedin_debug','on') }}"
            sequence:
              - service: system_log.write
                data:
                  level: warning
                  message: "{{ debug_v1 }}"

      # Debug-Log (Logbook)
      - choose:
          - conditions: "{{ is_state('input_boolean.solar_feedin_debug','on') }}"
            sequence:
              - service: logbook.log
                data:
                  name: "Solar Feed-in Loss"
                  message: >
                    ⚡ Einspeiseverlust:
                    prev={{ prev }} kWh,
                    curr={{ curr }} kWh,
                    Δ={{ delta_kwh | round(6) }} kWh,
                    price={{ price }} €/kWh,
                    Verlust={{ delta_loss_eur | round(6) }} €

      # Nur aktualisieren, wenn echter gültiger Wert
      - if:
          - "{{ delta_loss_eur | float(-9999) != 0 }}"
        then:
          - variables:
              debug_v2: >
                [DEBUG FEEDIN V2]
                saving_raw={{ states('input_number.saving_feedin_loss') }}
                saving_float={{ states('input_number.saving_feedin_loss') | float(-9999) }}
                delta={{ delta_loss_eur }}
                delta_float={{ delta_loss_eur | float(-9999) }}

          - choose:
              - conditions: "{{ is_state('input_boolean.solar_feedin_debug','on') }}"
                sequence:
                  - service: system_log.write
                    data:
                      level: warning
                      message: "{{ debug_v2 }}"

          - service: input_number.set_value
            target:
              entity_id: input_number.saving_feedin_loss
            data:
              value: "{{ (states('input_number.saving_feedin_loss') | float(-9999) + delta_loss_eur | float(0) ) | round(6) }}"
